"""empty message

Revision ID: 826cfe070dc1
Revises: 3364a8eb59f7
Create Date: 2018-09-09 12:38:34.795237

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '826cfe070dc1'
down_revision = '3364a8eb59f7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('dob', sa.String(length=80), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'dob')
    # ### end Alembic commands ###
